code/video_site/video_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('watch_me/', include('watch_me.urls')),
    path('', include('watch_me.urls')),
]

code/video_site/watch_me/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('profile', views.profile, name='profile'),
    path('profile/<int:id>', views.profile, name='profile'),
    path('notifications', views.notifications, name='notifications'),
    path('my_videos', views.my_videos, name='my_videos'),
    path('upload_video', views.upload_video, name='upload_video'),
    path('logout', views.logout, name='logout'),
    path('watch_video/<int:id>', views.watch_video, name='watch_video'),
    path('watch_video/comment/<int:id>', views.comment, name='comment'),
    path('playlists', views.playlists, name='playlists'),
    path('playlist/<int:id>', views.playlist, name='playlist'),
    path('add_playlist/<str:name>', views.add_playlist, name='add_playlist'),
    path('delete_playlist/<int:id>', views.delete_playlist, name='delete_playlist'),
    path('subscribe/<int:id>', views.subscribe, name='subscribe'),
    path('unsubscribe/<int:id>', views.unsubscribe, name='unsubscribe'),
    path('delete_profile/<int:id>', views.delete_profile, name='delete_profile'),
    path('subscribers/<int:id>', views.subscribers, name='subscribers'),
    path('like/<int:id>', views.like, name='like'),
    path('dislike/<int:id>', views.dislike, name='dislike'),
    path('liked_videos', views.liked_videos, name='liked_videos'),
    path('most_viewed', views.most_viewed, name='most_viewed'),
    path('most_viewed/<str:cat>', views.most_viewed, name='most_viewed'),
    path('most_active_users', views.most_active_users, name='most_active_users'),
    path('most_active_users/<str:filter>', views.most_active_users, name='most_active_users'),
    path('favorites', views.favorites, name='favorites'),
    path('delete_comment/<int:video>/<int:id>', views.delete_comment, name='delete_comment'),
    path('delete_notification/<int:id>/<int:video_id>', views.delete_notification, name='delete_notification'),
    path('delete_notification/<int:id>', views.delete_notification, name='delete_notification'),
    path('search', views.search, name='search'),
    path('watch_video/search', views.search, name='video_search'),
    path('playlist/search', views.search, name='playlist_search'),
    path('profile/search', views.search, name='profile_search'),
    path('users_who_likes/<int:video_id>', views.others_who_likes_video, name='users_who_likes'),
    path('delete_video/<int:id>', views.delete_video, name='delete_video'),
    path('edit_category/<int:id>/<str:new_name>', views.edit_category, name='edit_category'),
    path('delete_category/<int:id>', views.delete_category, name='delete_category'),
    path('add_category/<str:name>', views.add_category, name='add_category'),
    path('adminpanel', views.adminpanel, name='adminpanel'),
    path('send_feedback', views.send_feedback, name='send_feedback'),
    path('send_report', views.send_report, name='send_report'),
    path('watch_video/add_to_playlist', views.add_to_playlist, name='add_to_playlist'),
    path('watch_video/send_report', views.send_report, name='send_report'),
    path('videos_user/<int:userid>', views.videos_user, name='videos_user'),
    # path('watch_video/<int:id>/stats', views.stats_for_video, name='stats_for_video')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
app_name = 'watch_me'

code/video_site/watch_me/models.py
import datetime

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from .pathhelper import set_file_path, profile_path


class XCategory(models.Model):
    id = models.AutoField(primary_key=True, auto_created=True)
    name = models.CharField(max_length=20, null=False)

    class Meta:
        db_table = 'xcategory'

    def __str__(self):
        return self.name


class XCountry(models.Model):
    code = models.CharField(max_length=4, primary_key=True, null=True)
    name = models.CharField(max_length=100, null=False)

    class Meta:
        db_table = 'xcountry'

    def __str__(self):
        return f'{self.name}  '


class XUser(models.Model):
    id = models.AutoField(primary_key=True, null=False, auto_created=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    password = models.CharField(max_length=256)
    email = models.CharField(max_length=254)
    reg_date = models.DateTimeField(default=datetime.date.today, null=False, )
    country_code = models.ForeignKey(XCountry, on_delete=models.CASCADE)
    last_online = models.DateTimeField(null=True)
    picture = models.FileField(upload_to=profile_path, null=False)

    class Meta:
        db_table = 'xuser'

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class XVideo(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200, null=False)
    description = models.CharField(max_length=255, blank=True, null=True)
    binary = models.FileField(upload_to=set_file_path, null=False)
    thumbnail = models.FileField(upload_to=set_file_path, null=False)
    length = models.IntegerField(null=False)
    comments_on = models.IntegerField(null=False, validators=[MinValueValidator(0), MaxValueValidator(1)])
    category = models.ForeignKey(XCategory, on_delete=models.CASCADE)
    uploader = models.ForeignKey(XUser, on_delete=models.CASCADE)
    upload_date = models.DateTimeField(default=datetime.date.today, null=False)

    class Meta:
        db_table = 'xvideo'

    def __str__(self):
        return self.name


class XComments(models.Model):
    user = models.ForeignKey(XUser, on_delete=models.CASCADE)
    video = models.ForeignKey(XVideo, on_delete=models.CASCADE)
    c_date = models.DateTimeField(blank=True, null=True)
    c_text = models.CharField(max_length=254, blank=True, null=True)

    class Meta:
        db_table = 'xcomments'


class XFeedback(models.Model):
    xdate = models.DateField(blank=True, null=True)
    user = models.ForeignKey(XUser, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    rating = models.IntegerField(default=3, null=False, validators=[MinValueValidator(1), MaxValueValidator(5)])
    version = models.CharField(default="v1.0", max_length=5)

    class Meta:
        db_table = 'xfeedback'


class XLike(models.Model):
    user = models.ForeignKey(XUser, on_delete=models.CASCADE)
    video = models.ForeignKey(XVideo, on_delete=models.CASCADE)
    l_date = models.DateField(default=datetime.date.today)

    class Meta:
        db_table = 'xlike'


class XNotificatonType(models.Model):
    id = models.AutoField(primary_key=True)
    text = models.CharField(max_length=254, blank=True, null=True)

    class Meta:
        db_table = 'xnotificaton_type'

    def __str__(self):
        return self.text


class XNotification(models.Model):
    id = models.AutoField(primary_key=True)
    video = models.ForeignKey(XVideo, on_delete=models.CASCADE)
    user = models.ForeignKey(XUser, on_delete=models.CASCADE)
    n_type = models.ForeignKey(XNotificatonType, on_delete=models.CASCADE)
    sent_date = models.DateField(default=datetime.date.today)

    class Meta:
        db_table = 'xnotification'


class XPlaylist(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    c_date = models.DateField(default=datetime.date.today)
    creator_user = models.ForeignKey(XUser, on_delete=models.CASCADE)

    class Meta:
        db_table = 'xplaylist'

    def __str__(self):
        return self.name


class XplaylistVideo(models.Model):
    playlist = models.ForeignKey(XPlaylist, on_delete=models.CASCADE)
    video = models.ForeignKey(XVideo, on_delete=models.CASCADE)

    class Meta:
        db_table = 'xplaylist_video'

    def __str__(self):
        return self.playlist.name + ' | ' + self.video.name


class XReportTypes(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        db_table = 'xreport_types'


class XReport(models.Model):
    id = models.AutoField(primary_key=True)
    r_type = models.ForeignKey(XReportTypes, on_delete=models.CASCADE)
    r_text = models.CharField(max_length=254, blank=True, null=True)
    r_date = models.DateTimeField(auto_now_add=True, blank=True)
    r_video = models.ForeignKey(XVideo, on_delete=models.CASCADE)

    class Meta:
        db_table = 'xreport'


class XSearchHistory(models.Model):
    user = models.ForeignKey(XUser, on_delete=models.CASCADE)
    keyword = models.CharField(max_length=255, null=False)
    s_date = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'xsearch_history'


class XSubscribe(models.Model):
    from_u = models.ForeignKey(XUser, on_delete=models.CASCADE, related_name='from_id')
    to = models.ForeignKey(XUser, on_delete=models.CASCADE, related_name='to_id')

    class Meta:
        db_table = 'xsubscribe'

    def __str__(self):
        return str(self.from_u) + '->' + str(self.to)

class XTag(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        db_table = 'xtag'

    def __str__(self):
        return self.name


class XVideoTag(models.Model):
    video = models.ForeignKey(XVideo, on_delete=models.CASCADE)
    tag = models.ForeignKey(XTag, on_delete=models.CASCADE)

    class Meta:
        db_table = 'xvideo_tag'

    def __str__(self):
        return self.tag.name + '|' + self.video.name


class XWatchHistory(models.Model):
    user = models.ForeignKey(XUser, on_delete=models.CASCADE)
    video = models.ForeignKey(XVideo, on_delete=models.CASCADE)
    w_date = models.DateTimeField(auto_now_add=True, blank=True)

    class Meta:
        db_table = 'xwatch_history'

code/video_site/watch_me/forms.py
from django import forms
from .models import *


class XUserForm(forms.ModelForm):
    class Meta:
        model = XUser
        fields = {'id', 'first_name', 'last_name', 'password', 'email', 'country_code'}


class XVideoForm(forms.ModelForm):
    class Meta:
        model = XVideo
        fields = {'name', 'description', 'comments_on', 'category', 'id'}

code/video_site/watch_me/templates/projectx/addToPlaylistForm.html
{% load static %}
<form method="post" action="add_to_playlist" style="display: none" id="add_to_playlist_form">
    {% csrf_token %}
    <div class="report">
        <span>
            Hozzáadás a
            <select name="playlist_id">
                {% for playlist in playlists %}
                    <option value="{{ playlist.id }}">{{ playlist.name }}</option>
                {% endfor %}
            </select>
            lejátszási listához
        </span>
        <input type="text" style="display: none" value="{{ video_id }}" name="video_id">
        <span>
        <button type="submit" onclick="showAddPlaylistForm()">Hozzáadás</button>
        <button type="reset" onclick="hideAddPlaylistForm()">Mégse</button>
        </span>
    </div>
</form>

<script>
    function showAddPlaylistForm() {
        if (document.getElementById("add_to_playlist_form").style.display === "none")
            document.getElementById("add_to_playlist_form").style.display = "block"
        else if (document.getElementById("add_to_playlist_form").style.display === "block")
            document.getElementById("add_to_playlist_form").style.display = "none"
    }

    function hideAddPlaylistForm() {
        document.getElementById("add_to_playlist_form").style.display = "none"
        document.getElementById("add_playlist_button").style.display = "inline"
    }
</script>

code/video_site/watch_me/templates/projectx/adminpanel.html
<!DOCTYPE html>
{% load static %}
<html lang="hu">
<head>
    <meta charset="UTF-8">
    <title>Admin Panel</title>
    <link rel="icon" href="../../static/pictures/icons/logo-icon.png" type="image/icon type">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
    <link rel="stylesheet" href="{% static 'css/adminpanel.css' %}">
</head>
<body>
    {% include 'projectx/nav.html' %}

    <div class="data-container">
        <h1>Admin Panel</h1>
        <div class="admin-table">
            <table>
                <tr>
                    <td class="admin-column">
                        {% include 'projectx/incoming_feedback.html' %}
                    </td>
                    <td class="admin-column">
                        {% include 'projectx/reports.html' %}
                    </td>
                    <td class="admin-column">
                        {% include 'projectx/video_categories.html' %}
                    </td>
                </tr>
            </table>
        </div>
        <div class="question">
            <button onclick="window.location.href='{% url 'watch_me:most_active_users' %}';">Legaktívabb felhasználók</button>
        </div>
    </div>
</body>
</html>

code/video_site/watch_me/templates/projectx/dropdown.html
{% load static %}
<div class="dropdown">
    <div class="dropdown-background
    {% if request.session.user_id == 4206969 %} admin {% else %}
        {% if request.session.user_id > 0 %} logged {% else %} not-logged {% endif %}
    {% endif %}">
        <div class="dropdown-content">
            <a href="{% url 'watch_me:index' %}"><div><img src="../../static/pictures/icons/menu-icon.png">Fő oldal</div></a>
            {% if request.session.user_id > 0 %}
                <a href="{% url 'watch_me:notifications' %}"><div>
                    {% if notificaiton_count > 0 %} <div class="notifies"> {{ notificaiton_count }} </div> {% endif %} <img src="../../static/pictures/icons/bell-icon.png">Értesítések
                </div></a>
                <a href="{% url 'watch_me:profile' %}"><div><img src="../../static/pictures/icons/profile-icon.png">Profil</div></a>
                <a href="{% url 'watch_me:favorites' %}"><div><img src="../../static/pictures/icons/star-icon.png">Kedvencek</div></a>
                <a href="{% url 'watch_me:my_videos' %}"><div><img src="../../static/pictures/icons/video-icon.png">Videóim</div></a>
                <a href="{% url 'watch_me:playlists'  %}"><div><img src="../../static/pictures/icons/playlist-icon.png">Lejátszási listák</div></a>
                {% if request.session.user_id == 4206969 %}
                    <a href="{% url 'watch_me:adminpanel'  %}"><div><img src="../../static/pictures/icons/admin-icon.png">Admin Panel</div></a>
                {% endif %}
                <a href="{% url 'watch_me:logout' %}"><div><img src="../../static/pictures/icons/door-icon.png">Kijelentkezés</div></a>
            {% else %}
                <a href="{% url 'watch_me:login' %}"><div><img src="../../static/pictures/icons/door-icon.png">Bejelentkezés</div></a>
            {% endif %}
        </div>
    </div>
    <a href="{% url 'watch_me:profile' %}">
        {% if request.session.user_id > 0 %}
            <div class="profile-name">{{ request.session.user_name }}</div>
        {% else %}
            <div class="profile-name"> Vendég </div>
        {% endif %}
        <div class="profile-picture-container">
            <div class="profile-picture">
                {% if request.session.user_id > 0 %}
                    <img src="../../../watch_me/media/{{ request.session.user_id }}/profile.jpg" alt="profile-picture">
                {% else %}
                    <img src="{% static 'pictures/profile.png' %}" alt="profile-picture">
                {% endif %}
            </div>
        </div>
    </a>
</div>

code/video_site/watch_me/templates/projectx/liked_videos.html
<!DOCTYPE html>
{% load static %}
<html lang="hu">
<head>
    <meta charset="UTF-8" >
    <title>Watch me!</title>
    <link rel="icon" href="../../static/pictures/icons/logo-icon.png" type="image/icon type">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
    {% include 'projectx/nav.html' %}
    <h1> Kedvelt videóid:</h1>
    <div class="videos">
        {% for video in videos %}
        <a href="{% url 'watch_me:watch_video' video.id %}" class="video-card">
            <img src="../../../watch_me/media/{{ video.thumbnail.name }}" alt="thumbnail">
            <div class="video-title">{{ video.name }}</div>
            <div class="video-author">{{ video.uploader.first_name }} {{ video.uploader.last_name }}</div>
        </a>
        {% endfor %}
    </div>
</body>
</html>

code/video_site/watch_me/templates/projectx/logo.html
{% load static %}
<a href="{% url 'watch_me:index' %}"><div class="logo">
    <img src="{% static 'pictures/logo.png' %}" alt="Logó">
</div></a>

code/video_site/watch_me/templates/projectx/my_videos.html
<!DOCTYPE html>
{% load static %}
<html lang="hu">
<head>
    <meta charset="UTF-8">
    <title>Watch me! - Videóim</title>
    <link rel="icon" href="../../static/pictures/icons/logo-icon.png" type="image/icon type">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
    {% include 'projectx/nav.html' %}

    <div class="videos">
        {% if request.session.user_id > 0 %}
            {% for video in videos %}

            <div class="video-card">
                <a href="{% url 'watch_me:watch_video' video.id %}">
                    <img src="../../../watch_me/media/{{ video.thumbnail.name }}" alt="thumbnail">
                    <div class="video-title">{{ video.name }}</div>
                    <div class="video-author">{{ video.uploader.first_name }} {{ video.uploader.last_name }}</div>
                </a>
                <a href={% url 'watch_me:delete_video' video.id %}><button>Törlés</button></a>
            </div>

            {% endfor %}

            <a href="{% url 'watch_me:upload_video' %}" class="video-card">
                <object data="">
                    <span>+</span>
                </object>
                <div class="video-title">Videó feltöltése</div>
                <div class="safe-space"></div>
            </a>
        {% endif %}
    </div>

    {% include "projectx/send_feedback.html" %}
</body>
</html>

code/video_site/watch_me/templates/projectx/nav.html
{% load static %}
<div class="background"></div>

<header>
    {% include 'projectx/logo.html' %}

    {% include 'projectx/searchbar.html' %}

    {% include 'projectx/dropdown.html' %}
</header>

code/video_site/watch_me/templates/projectx/playlist.html
<!DOCTYPE html>
{% load static %}
<html lang="hu">
<head>
    <meta charset="UTF-8" >
    <title>Watch me! - {{ playlist.name }}</title>
    <link rel="icon" href="../../static/pictures/icons/logo-icon.png" type="image/icon type">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
    <link rel="stylesheet" href="{% static 'css/playlist.css' %}">
</head>
<body>
    {% include 'projectx/nav.html' %}

    <div class="fav">
        {% if request.session.user_id == playlist.creator_user_id %}
            <button onclick="window.location.href='{% url 'watch_me:delete_playlist' playlist.id %}';">Lejátszási lista törlése ❌</button>
        {% endif %}
        <h1>{{ playlist.name }}</h1>
        {% for video in videos %}
            <div>
                <hr>
                <video controls preload autoplay>
                    <source src="../../../watch_me/media/{{ video.binary.name }}" type="video/mp4">
                </video>
                <a href="{% url 'watch_me:watch_video' video.id %}">{{ video.name }}</a>
            </div>
        {% endfor %}
    </div>

</body>
</html>

code/video_site/watch_me/templates/projectx/playlists.html
<!DOCTYPE html>
{% load static %}
<html lang="hu">
<head>
    <meta charset="UTF-8" >
    <title>Watch me! - Lejátszási listák</title>
    <link rel="icon" href="../../static/pictures/icons/logo-icon.png" type="image/icon type">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
    <link rel="stylesheet" href="{% static 'css/data_form.css' %}">
</head>
<body>
    {% include 'projectx/nav.html' %}

    <div class="data-container">
        <h1>Lejátszási listák</h1>
        <div class="data">
            <div class="link-box">
                {% for ps in play_lists %}
                    <a href={% url 'watch_me:playlist' ps.id %}>{{ ps.name }} ({{ ps.net_view }} megtekintés)</a><hr>
                {% endfor %}
            </div>
            <div class="question">
                <div id="containerq">
                    <input type="button" value="➕ Lejátszási lista hozzáadása" onclick="add_playlist('show')" id="add_new">
                </div>
            </div>
        </div>
    </div>

    <script>
        function add_playlist(mode) {
            if (mode === "show") {
                textField = document.createElement("input")
                textField.type = "text"
                textField.id = "newnameField"
                document.getElementById("containerq").insertBefore(textField, document.getElementById("add_new"))
                document.getElementById("add_new").setAttribute("value", "✓")
                document.getElementById("add_new").setAttribute("onclick", `add_playlist("execute")`)
            } else {
                console.log("editing")
                if (document.getElementById("newnameField").value !== "") {
                    console.log(`Adding category ${document.getElementById("newnameField").value}`)
                    window.location.href = `/add_playlist/${document.getElementById("newnameField").value}`
                } else {
                    console.log("cancelled edit")
                    document.getElementById("newnameField").remove()
                    document.getElementById("add_new").setAttribute("value", "➕ Lejátszási lista")
                    document.getElementById("add_new").setAttribute("onclick", `add_playlist("show")`)
                }
            }
        }
    </script>

</body>
</html>

code/video_site/watch_me/templates/projectx/profile.html
<!DOCTYPE html>
{% load static %}
<html lang="hu">
<head>
    <meta charset="UTF-8">
    <title>Watch me! - {{ user.first_name }} {{ user.last_name }}</title>
    <link rel="icon" href="../../static/pictures/icons/logo-icon.png" type="image/icon type">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
    <link rel="stylesheet" href="{% static 'css/data_form.css' %}">
</head>
<body>
    {% include 'projectx/nav.html' %}

    <div class="data-container">
        <h1>
            <div class="img-mask"><img src="../../../watch_me/media/{{ user.picture.name }}" alt="profile-picture"/></div>
            {{ user.first_name }} {{ user.last_name }}
        </h1>
        <div class="data profile">
            <table>
                <tr>
                    <td>E-mail:</td>
                    <td>{{ user.email }}</td>
                </tr>
                <tr>
                    <td>Ország:</td>
                    <td>{{ user.country_code }}</td>
                </tr>
                <tr>
                    <td>Regisztráció időpontja:</td>
                    <td>{{ user.reg_date }}</td>
                </tr>
                <tr>
                    <td>Legutóbb bejelentkezve:</td>
                    <td>{% if user.last_online == None %} Soha {% else %} {{ user.last_online }} {% endif %}</td>
                </tr>
                <tr>
                    <td>Felíratkozott személyek:</td>
                    <td><a href={% url 'watch_me:subscribers' user.id %}>{{ sub_count }} személy</a></td>
                </tr>
                <tr>
                    <td>Videók:</td>
                    {% if request.session.user_id == user.id %}
                        <td><a href="{% url 'watch_me:my_videos' %}">{{ video_count }} videó</a></td>
                    {% else %}
                        <td><a href="{% url 'watch_me:videos_user' user.id %}">{{ video_count }} videó</a></td>
                    {% endif %}
                </tr>
            </table>
            <div class="question">
                {% if user.id != request.session.user_id %}
                    {% if is_subbed %}
                        <a href="{% url 'watch_me:unsubscribe' user.id %}">Leíratkozás</a>
                    {% else %}
                        <a href="{% url 'watch_me:subscribe' user.id %}">Felíratkozás</a>
                    {% endif %}
                {% elif request.session.user_id == user.id %}
                    <button onclick="deleteProfile()">Profil törlése</button>
                    <script>
                        function deleteProfile() {
                            let text = "Biztos, hogy törölni szeretnéd a profilod?";
                            if (confirm(text) === true) {
                                alert(`{{ user.first_name }} {{ user.last_name }} sikeresen törölve!`);
                                window.location.replace(window.location.href.replace("profile", "delete_profile/" + {{ user.id }}));
                            }
                        }
                    </script>
                {% endif %}
            </div>
        </div>
    </div>
</body>
</html>

code/video_site/watch_me/templates/projectx/upload_video.html
<!DOCTYPE html>
{% load static %}
<html lang="hu">
<head>
    <meta charset="UTF-8">
    <title>Videó feltöltése</title>
    <link rel="icon" href="../../static/pictures/icons/logo-icon.png" type="image/icon type">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
    <link rel="stylesheet" href="{% static 'css/data_form.css' %}">
</head>
<body>
    {% include 'projectx/nav.html' %}

    <div class="data-container">
        <h1>Videó feltöltése</h1>
        <div class="data profile">
            <form method="post" action="upload_video" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="upload-video">
                    <tr>
                        <td><label for="id_name">Videó címe:</label></td>
                        <td><input type="text" id="id_name" name="v_name" maxlength="50"></td>
                    </tr>
                    <tr>
                        <td><label for="id_video">Fájl kiválasztása:</label></td>
                        <td><input type="file" accept="video/mp4,video/x-m4v,video/*" id="id_video" name="v_video"></td>
                    </tr>
                    <tr>
                        <td><label for="id_thumbnail">Indexkép:</label></td>
                        <td><input type="file" accept="image/x-png,image/gif,image/jpeg" id="id_thumbnail" name="v_tn"></td>
                    </tr>
                    <tr>
                        <td><label for="id_desc">Leírás:</label></td>
                        <td><input type="text" id="id_desc" name="v_desc" maxlength="255"></td>
                    </tr>
                    <tr>
                    <tr>
                        <td><label for="id_comment">Hozzászólások engedélyezése:</label></td>
                        <td>
                            <input type="checkbox" checked="checked" id="id_comment" name="v_comment">
                            <div class="checkmark"></div>
                        </td>
                    </tr>
                    <tr>
                        <td><label for="id_{{ field.name }}" >Kategória:</label></td>
                        <td>
                            {% for field in video_form %}
                                {% if field.name == 'category' %}
                                    {{ field }}
                                {% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td><label for="id_tags" class="tooltip">Címkék:<span class="tooltiptext">Vesszővel elválasztva, pl:<br>game,tutorial</span></label></td>
                        <td><input type="text" id="id_tags" name="v_tags" maxlength="255"></td>
                    </tr>
                    <tr>
                        <th colspan="2"><input type="submit" value="Feltöltés"></th>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</body>
</html>

code/video_site/watch_me/templates/projectx/users_who_likes.html
<!DOCTYPE html>
{% load static %}
<html lang="hu">
<head>
    <meta charset="UTF-8" >
    <title>Watch me! - Akik kedvelik a videót</title>
    <link rel="icon" href="../../static/pictures/icons/logo-icon.png" type="image/icon type">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
    <link rel="stylesheet" href="{% static 'css/data_form.css' %}">
</head>
<body>
    {% include 'projectx/nav.html' %}

    <div class="data-container">
        <h1>Akik kedvelik a videót</h1>
        <div class="data">
            <div class="link-box">
                {% for user in users %}
                    <a href={% url 'watch_me:profile' user.id %}> {{ user.user_name }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
</html>